travis:
  secure:
    BINSTAR_TOKEN: hypWNTKCckfGaeYA64/RfGAUUrt/slJF2RCAkFfBsSdm2+kDWe2gS6YXndVzySd01LCZvIIA8S+DoJ7q5A9YxNNgkyzPVeOWtgDmAFW9sREB0svjHiD/amzdH6s8zKsA44KTllA+nu9bu6MZQKFtEhTVu+9ayvrbcVPa1fv15/aiSVMfxSb4zN7sKJoWGP13KWyK5xkTVhEAhlSUTetEG6rDWQzjHfL5x82x4Aof56Mb99T8NTnVQNy97cYtktepd69m+lqmaOTSrwLr9jDpZlN4JG9k4yeXkpqvQVr7Ra3VZaqSIpS1An7n/ZcL+8q4ezHQiJ/RwMyCHWiBNdAOsYUb/gSTNJXl4Ai7U3AUXOamA16EH5RmFh2HdiPKdAlZF70sC0+zAjgjfsn51L9OmiL8LW3kMKthWaUQ+Y3Pr3jhQ9cOsFCIAGQ8zfTmupEXiZNOU6mTE+isQRAO3nahf4CQ5XjsDeqM+NlVlOY6R3UzsclXZbu4HsgvGR8iIS8CfwabZKhIhyHj8Ge/YjbJ0HId1hykxz+e9p6dwt878nhmRnz+j7krZxLIUvQ31W1d0Zo+5nW1IHtRpNWUCTAFQjGywhZVyJuZkW99BcNPtEZ0UN7T41hY2kqy3Qq4Xph+mlNVrlRU4gAvEf4kirXULa8qkfIEjv9PXPR3kBpuiG8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
